### ISSUE TITLE
Интерфейс страницы ПЛЮС

### ISSUE THREAD

**Issue by vanja-san** [StaticHUN/KinOnline#1]
Где искать кнопку на такой странице? Если нет, добавьте пожалуйста:
<details>
  <summary>Скриншот</summary>

  ![изображение](https://user-images.githubusercontent.com/7201687/188747446-7eb2ea55-0646-44bc-91fc-b7156ce49ed2.png)

</details>

**Comment by StaticHUN** [comment]
@vanja-san Добавил проверку на отсутствие подписки. Кнопка расположена в стандартном месте (Вверху постера)

**Comment by vanja-san** [comment]
@StaticHUN то есть если у меня нет подписки, то кнопки не будет видно? Т.к. у меня всё ещё не появилась кнопка
Браузер: Файрфокс
Расширение: Тампермонкей

**Comment by StaticHUN** [comment]
@vanja-san Кнопка не будет отображаться если открыта страница не с фильмом\сериалом или фильм\сериал входит в подписку.

Поправил отображение кнопки в разных браузерах.
Необходимо обновить версию скрипта в Tampermonkey.
